name: Update JBZD Profiles

on:
  schedule:
    # co godzinę
    - cron: '0 * * * *'
  workflow_dispatch: # umożliwia uruchomienie ręczne

jobs:
  update-profiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_dzidowcow.py

      - name: Commit updated CSV
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add lista_dzidowcow.csv
          git commit -m "Update JBZD profiles"
          git push
